"""models.py

Revision ID: d208ed7fcb32
Revises: 3eedec15128c
Create Date: 2023-08-30 13:33:30.221367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd208ed7fcb32'
down_revision = '3eedec15128c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
